apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - name: http
    port: 3000
    nodePort: 32000
    protocol: TCP
